# ============================================================
# src/evaluator.py
# RAGAS evaluation using Google Gemini Flash
# ============================================================

from __future__ import annotations

import json
import logging
import math
import os
import time
from pathlib import Path
from typing import List, Dict, Any, Optional

from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from ragas.llms       import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from datasets import Dataset

from langchain_community.embeddings import HuggingFaceEmbeddings

logger = logging.getLogger(__name__)

_METRICS      = [faithfulness, answer_relevancy, context_precision, context_recall]
_METRIC_NAMES = ["faithfulness", "answer_relevancy", "context_precision", "context_recall"]


def _sanitize_for_json(value: Any) -> Any:
    """Replace NaN/Infinity with None so JSON output is valid."""
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        return value
    if isinstance(value, dict):
        return {k: _sanitize_for_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_sanitize_for_json(v) for v in value]
    return value


def _build_gemini_llm():
    """Google Gemini 1.5 Flash — free tier, generous rate limits."""
    api_key = os.environ.get("GOOGLE_API_KEY", "")
    # FIX: validate the key upfront so the user gets a clear error instead of
    # a cryptic failure deep inside the RAGAS call stack.
    if not api_key:
        raise EnvironmentError(
            "GOOGLE_API_KEY is not set. "
            "Get a free key at https://aistudio.google.com/app/apikey "
            "and set it as an environment variable or enter it in the UI."
        )
    try:
        from langchain_google_genai import ChatGoogleGenerativeAI
        return ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0)
    except ImportError:
        raise ImportError(
            "langchain-google-genai not installed. "
            "Run: pip install langchain-google-genai"
        )


def _build_embedding_wrapper():
    hf_emb = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    return LangchainEmbeddingsWrapper(hf_emb)


def _dataset_to_ragas(samples: List[Dict[str, Any]]) -> Dataset:
    """
    Convert internal format to the HuggingFace Dataset RAGAS expects.

    FIX: original fell back to ground_truth when 'answer' was missing,
    which caused the evaluator to compare ground_truth against itself and
    report artificially perfect scores.  Now raises clearly if answer is absent.
    """
    rows: Dict[str, list] = {
        "question":     [],
        "answer":       [],
        "contexts":     [],
        "ground_truth": [],
    }
    for i, s in enumerate(samples):
        if "answer" not in s:
            raise ValueError(
                f"Sample {i} is missing the 'answer' field. "
                "Each sample must have question, answer, contexts, and ground_truth."
            )
        rows["question"].append(s["question"])
        rows["answer"].append(s["answer"])
        rows["contexts"].append(s.get("contexts", [s.get("ground_truth", "")]))
        rows["ground_truth"].append(s["ground_truth"])

    return Dataset.from_dict(rows)


class RAGEvaluator:
    """
    Runs RAGAS evaluation over a sample list.

    Usage:
        evaluator = RAGEvaluator()
        results   = evaluator.evaluate(samples)
    """

    RESULTS_PATH = "data/eval_results.json"

    def __init__(self):
        self._llm_wrapper: Optional[LangchainLLMWrapper]         = None
        self._emb_wrapper: Optional[LangchainEmbeddingsWrapper]  = None

    def _init_llm(self):
        llm = _build_gemini_llm()   # raises clearly if GOOGLE_API_KEY not set
        self._llm_wrapper = LangchainLLMWrapper(llm)
        logger.info("[RAGEvaluator] Using Google Gemini 1.5 Flash as judge LLM.")

    def _init_embeddings(self):
        self._emb_wrapper = _build_embedding_wrapper()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate(
        self,
        samples: List[Dict[str, Any]],
        save_path: str = RESULTS_PATH,
        force_reinit: bool = False,
    ) -> Dict[str, Any]:
        """
        Run RAGAS on `samples`.

        Each sample must have:
            question      str
            answer        str   (generated by RAG system)
            contexts      list[str]
            ground_truth  str
        """
        if not samples:
            raise ValueError("No samples provided for evaluation.")

        if self._llm_wrapper is None or force_reinit:
            self._init_llm()
        if self._emb_wrapper is None:
            self._init_embeddings()

        for metric in _METRICS:
            metric.llm = self._llm_wrapper
            if hasattr(metric, "embeddings"):
                metric.embeddings = self._emb_wrapper

        dataset = _dataset_to_ragas(samples)

        result = evaluate(dataset, metrics=_METRICS)

        scores     = result.to_pandas()
        aggregate  = {
            name: round(float(scores[name].mean()), 4)
            for name in _METRIC_NAMES
            if name in scores.columns
        }
        per_sample = scores.to_dict(orient="records")

        output = {
            "aggregate":   _sanitize_for_json(aggregate),
            "per_sample":  _sanitize_for_json(per_sample),
            "num_samples": len(samples),
            "timestamp":   time.strftime("%Y-%m-%dT%H:%M:%S"),
        }

        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        with open(save_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)

        logger.info("[RAGEvaluator] Results saved → %s", save_path)
        return output

    @staticmethod
    def load(path: str = RESULTS_PATH) -> Optional[Dict[str, Any]]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return _sanitize_for_json(json.load(f))
        except FileNotFoundError:
            return None