# ============================================================
# src/evaluator.py
# RAGAS evaluation using Google Gemini Flash
# ============================================================

from __future__ import annotations

import json
import math
import time
from pathlib import Path
from typing import List, Dict, Any, Optional

# RAGAS imports
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from ragas.llms  import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from datasets import Dataset

# LangChain LLM wrappers
from langchain_community.embeddings import HuggingFaceEmbeddings


_METRICS = [faithfulness, answer_relevancy, context_precision, context_recall]
_METRIC_NAMES = ["faithfulness", "answer_relevancy", "context_precision", "context_recall"]


def _build_groq_llm(model: str = "llama-3.3-70b-versatile"):
    """Kept for backward compatibility; evaluation now uses Gemini only."""
    return None


def _sanitize_for_json(value: Any) -> Any:
    """Replace NaN/Infinity with None so JSON output is valid."""
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        return value
    if isinstance(value, dict):
        return {k: _sanitize_for_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_sanitize_for_json(v) for v in value]
    return value


def _build_gemini_llm():
    """Google Gemini 1.5 Flash — free tier, generous rate limits."""
    try:
        from langchain_google_genai import ChatGoogleGenerativeAI
        return ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0)
    except ImportError:
        raise ImportError(
            "langchain-google-genai not installed. "
            "Run: pip install langchain-google-genai"
        )


def _build_embedding_wrapper():
    """Reuse all-MiniLM-L6-v2 — already present in the project."""
    hf_emb = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    return LangchainEmbeddingsWrapper(hf_emb)


def _dataset_to_ragas(samples: List[Dict[str, Any]]) -> Dataset:
    """
    Convert our internal format to the HuggingFace Dataset RAGAS expects.

    RAGAS expects columns: question, answer, contexts, ground_truth
    """
    rows = {
        "question":     [],
        "answer":       [],
        "contexts":     [],
        "ground_truth": [],
    }
    for s in samples:
        rows["question"].append(s["question"])
        rows["answer"].append(s.get("answer", s.get("ground_truth", "")))
        rows["contexts"].append(s.get("contexts", [s.get("ground_truth", "")]))
        rows["ground_truth"].append(s["ground_truth"])

    return Dataset.from_dict(rows)


class RAGEvaluator:
    """
    Runs RAGAS evaluation over a sample list.

    Usage:
        evaluator = RAGEvaluator()
        results   = evaluator.evaluate(samples)  # list of {question, answer, contexts, ground_truth}
    """

    RESULTS_PATH = "data/eval_results.json"

    def __init__(self, prefer_groq: bool = False):
        self.prefer_groq = prefer_groq
        self._llm_wrapper   = None
        self._emb_wrapper   = None

    def _init_llm(self, force_gemini: bool = False):
        llm = _build_gemini_llm()
        self._llm_wrapper = LangchainLLMWrapper(llm)
        print("[RAGEvaluator] Using Google Gemini 1.5 Flash as judge LLM.")

    def _init_embeddings(self):
        self._emb_wrapper = _build_embedding_wrapper()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate(
        self,
        samples: List[Dict[str, Any]],
        save_path: str = RESULTS_PATH,
        force_gemini: bool = False,
    ) -> Dict[str, Any]:
        """
        Run RAGAS on `samples`.

        Each sample must have:
            question      str
            answer        str   (generated by RAG system)
            contexts      list[str]
            ground_truth  str

        Returns dict with per-metric scores + per-sample breakdown.
        """
        if not samples:
            raise ValueError("No samples provided for evaluation.")

        # Lazy init
        if self._llm_wrapper is None:
            self._init_llm(force_gemini=force_gemini)
        if self._emb_wrapper is None:
            self._init_embeddings()

        # Wire metrics to our LLM + embeddings
        for metric in _METRICS:
            metric.llm        = self._llm_wrapper
            if hasattr(metric, "embeddings"):
                metric.embeddings = self._emb_wrapper

        dataset = _dataset_to_ragas(samples)

        try:
            result = evaluate(dataset, metrics=_METRICS)
        except Exception:
            self._init_llm(force_gemini=True)
            for metric in _METRICS:
                metric.llm = self._llm_wrapper
            result = evaluate(dataset, metrics=_METRICS)

        # Build output
        scores = result.to_pandas()
        aggregate = {
            name: round(float(scores[name].mean()), 4)
            for name in _METRIC_NAMES
            if name in scores.columns
        }
        per_sample = scores.to_dict(orient="records")

        output = {
            "aggregate": _sanitize_for_json(aggregate),
            "per_sample": _sanitize_for_json(per_sample),
            "num_samples": len(samples),
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        }

        # Persist
        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        with open(save_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)

        print(f"[RAGEvaluator] Results saved → {save_path}")
        return output

    @staticmethod
    def load(path: str = RESULTS_PATH) -> Optional[Dict[str, Any]]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return _sanitize_for_json(json.load(f))
        except FileNotFoundError:
            return None
